### PR TITLE
Release 8x.25.3

### PR DESCRIPTION
**Pull request by tarrow**

### CODE REVIEW

**Review by m90 — APPROVED** [review]

**Comment by m90** [comment]
Do we wanna sneak https://github.com/wbstack/api/pull/673 in this release as well?

**Comment by tarrow** [comment]
eh sure; I'll let you merge 673

**Comment by m90** [comment]
@tarrow Done so

**Comment by tarrow** [comment]
pretty sure I never learn :P . Folding two changes into one release always seems like it would save time but really it just makes the reverts more painful

**Pull request merged**
