### PR TITLE
Use mxl/laravel-job instead of our own jobs

### PR DESCRIPTION
**Pull request by addshore**
https://phabricator.wikimedia.org/T298753

### CODE REVIEW

**Comment by deer-wmde** [comment]
I tried running `php artisan job:dispatchNow ProvisionQueryserviceNamespaceJob` which worked.
Running `php artisan wbs-job:dispatch ProvisionWikiDbJob` works on main, but with this code I get connection issues with the DB. Maybe I'm missing some env vars or something for the credentials?

https://phabricator.wikimedia.org/P18477

**Comment by toban** [comment]
> I tried running `php artisan job:dispatchNow ProvisionQueryserviceNamespaceJob` which worked. Running `php artisan wbs-job:dispatch ProvisionWikiDbJob` works on main*, but with this code I get connection issues with the DB. Maybe I'm missing some env vars or something for the credentials?
> 
> https://phabricator.wikimedia.org/P18477
> 
> * where it's `php artisan wbs-job:dispatch ProvisionWikiDbJob` of course

Did you get to the bottom of why you weren't able to connect?

**Review by toban — APPROVED** [review]
LGTM and seems to work

**Comment by toban** [comment]
@addshore could you rebase this on your computer?

**Comment by addshore** [comment]
> @addshore could you rebase this on your computer?

Doing now!

**Pull request merged**
